- name: Configure OCI Instance (OS, Kubernetes, MySQL)
  hosts: all
  become: yes
  roles:
    - role: os
      tags: os
    - role: kubernetes
      tags: kubernetes
    - role: mysql
      tags: mysql
